/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define FAST 100000
#define MEDIUM 300000
#define SLOW 1000000
#define WAIT(CNT)                                                              \
  do {                                                                         \
    for (int def_i = 0; def_i < CNT; def_i++)                                  \
      ;                                                                        \
  } while (0)

/******* PINS *********/
#define LED_GREEN_PORT GPIOB
#define LED_GREEN_PIN 0
#define LED_YELLOW_PORT GPIOE
#define LED_YELLOW_PIN 1
#define LED_RED_PORT GPIOB
#define LED_RED_PIN 14

#define USER_PBUTTON_PORT GPIOC
#define USER_PBUTTON_PIN 13

/********* SPI ********/

#define SPI1_GPIO_PORT GPIOA
#define SPI1_CLOCK_PIN 5
#define SPI1_NSS_PIN 4
#define SPI1_MISO_PIN 6
#define SPI1_MOSI_PIN 7
#define SPI1_ALT_FN 5

#define SPI2_GPIO_PORT GPIOB
#define SPI2_CLOCK_PIN 13
#define SPI2_NSS_PIN 12
#define SPI2_MISO_PIN 14
#define SPI2_MOSI_PIN 15
#define SPI2_ALT_FN 5

/* SPI3 uses multiple ports generally */

#define SPI4_GPIO_PORT GPIOE
#define SPI4_CLOCK_PIN 2
#define SPI4_NSS_PIN 4
#define SPI4_MISO_PIN 5
#define SPI4_MOSI_PIN 6
#define SPI4_ALT_FN 5

#define SPI5_GPIO_PORT GPIOF
#define SPI5_CLOCK_PIN 7
#define SPI5_NSS_PIN 6
#define SPI5_MISO_PIN 8
#define SPI5_MOSI_PIN 9
#define SPI5_ALT_FN 5

#define SPI6_GPIO_PORT GPIOG
#define SPI6_CLOCK_PIN 13
#define SPI6_NSS_PIN 8
#define SPI6_MISO_PIN 12
#define SPI6_MOSI_PIN 14
#define SPI6_ALT_FN 5

/*********** END SPI ********/

/********* TIMERS **********/

#define TIMER_16_GPIO_PORT GPIOF
#define TIMER_16_CH1_PIN 6
#define TIMER_16_CH1N_PIN 8
#define TIMER_16_ALT_FN 1

#define TIMER_17_GPIO_PORT GPIOF
#define TIMER_17_CH1_PIN 7
#define TIMER_17_CH1N_PIN 9
#define TIMER_17_ALT_FN 1

/******* END TIMERS ********/

#include <stdint.h>
#include <string.h>

#include "stm32h723xx.h"
#include "stm32h723xx_gpio.h"
#include "stm32h723xx_spi.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                       \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void program_init(void);

int main(void) {

  program_init();

  GPIO_peri_clock_control(TIMER_16_GPIO_PORT, ENABLE);
  GPIO_Handle_t gpio_handle;
  GPIO_RegDef_t **addr = &gpio_handle.p_GPIO_x;
  GPIO_PinConfig_t *cfg = &gpio_handle.GPIO_pin_config;

  *addr = TIMER_16_GPIO_PORT;
  cfg->GPIO_pin_number = TIMER_16_CH1_PIN;
  cfg->GPIO_pin_mode = GPIO_MODE_ALTFN;
  cfg->GPIO_pin_alt_func_mode = TIMER_16_ALT_FN;
  GPIO_init(&gpio_handle);

  // Start the peripheral clock for timer 16
  TIM16_PCLK_EN();

  // Set Compare Cpature Register to 60,000
  TIM16->CCR1 = 0;
  TIM16->ARR = 10000;

  // Enable CC1 interrupt
  TIM16->DIER |= (1 << TIM_DIER_CC1IE);
  TIM16->EGR |= (1 << TIM_EGR_CC1G);

  // Set up as up counting mode

  // Set up timer as output mode
  TIM16->CCMR1 &= ~(1 << TIM_CCMR1_CC1S);
  // TIM16->CCER |= (1 << TIM_CCER_CC1E);

  // Set prescalar so osc can follow
  TIM16->PSC = 512;

  // Lastly, enable counter
  TIM16->CR1 |= (1 << TIM_CR1_CEN);

  // Enable NVIC interrupt for Timer16
  NVIC->ISER[IRQ_NO_TIM16 / 32] |= (1 << (IRQ_NO_TIM16 % 32));

  /* Loop forever */
  for (;;) {
    // GPIO_toggle_output_pin(LED_GREEN_PORT, LED_GREEN_PIN);
    WAIT(SLOW);
  }
}

void program_init(void) {
  SYSCFG_PCLK_EN();

  // User button PC13
  // LED is on PB0
  GPIO_peri_clock_control(USER_PBUTTON_PORT, ENABLE);
  GPIO_peri_clock_control(LED_GREEN_PORT, ENABLE);

  // Create GPIO handler and assign shortcuts for easier access
  GPIO_Handle_t gpio_handle;
  GPIO_RegDef_t **addr = &gpio_handle.p_GPIO_x;
  GPIO_PinConfig_t *cfg = &gpio_handle.GPIO_pin_config;

  // User button PC13
  *addr = USER_PBUTTON_PORT;
  cfg->GPIO_pin_number = USER_PBUTTON_PIN;
  cfg->GPIO_pin_mode = GPIO_MODE_IT_FT;
  cfg->GPIO_pin_speed = GPIO_SPEED_LOW;
  cfg->GPIO_pin_pupd_control = GPIO_PUPDR_PULLDOWN;
  cfg->GPIO_pin_out_type = 0;
  cfg->GPIO_pin_alt_func_mode = 0;
  GPIO_init(&gpio_handle);
  GPIO_irq_interrupt_config(IRQ_NO_EXTI15_10, ENABLE);
  // GPIO_irq_priority_config(IRQ_NO_EXTI15_10, USER_PBUTTON_PIN);

  // LED PB0
  *addr = LED_GREEN_PORT;
  cfg->GPIO_pin_number = LED_GREEN_PIN;
  cfg->GPIO_pin_mode = GPIO_MODE_OUT;
  cfg->GPIO_pin_speed = GPIO_SPEED_LOW;
  cfg->GPIO_pin_pupd_control = GPIO_PUPDR_NONE;
  cfg->GPIO_pin_out_type = GPIO_OP_TYPE_PUSHPULL;
  cfg->GPIO_pin_alt_func_mode = 0;
  GPIO_init(&gpio_handle);

  int asdf2 = 0;
  asdf2 = 44;
}

void TIM16_IRQHandler(void) {
  // Clear Timer16 interrupt
  TIM16->SR &= ~(1 << TIM_SR_CC1IF);

  static int cnt = 0;

  cnt = (cnt + 1) % 5;

  if (!cnt)
    GPIO_toggle_output_pin(LED_GREEN_PORT, LED_GREEN_PIN);
}

void EXTI15_10_IRQHandler(void) {
  if (GPIO_irq_handling(USER_PBUTTON_PIN))
    GPIO_toggle_output_pin(LED_GREEN_PORT, LED_GREEN_PIN);
}
