/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define FAST 100000
#define MEDIUM 300000
#define SLOW 1000000
#define WAIT(CNT)                                                              \
  do {                                                                         \
    for (int def_i = 0; def_i < CNT; def_i++)                                  \
      ;                                                                        \
  } while (0)

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "stm32h723xx.h"
#include "stm32h723xx_gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                       \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void program_init(void);

int main(void) {
  program_init();

  /* Loop forever */
  for (;;)
    ;
}

void program_init(void) {
  // User button PC13
  // LED is on PB0
  GPIO_peri_clock_control(GPIOC, ENABLE);
  GPIO_peri_clock_control(GPIOE, ENABLE);

  GPIO_Handle_t gpio_handle;
  GPIO_RegDef_t **addr = &gpio_handle.p_GPIO_x;
  GPIO_PinConfig_t *cfg = &gpio_handle.GPIO_pin_config;

  // User button PC13
  *addr = GPIOC;
  cfg->GPIO_pin_number = 13;
  cfg->GPIO_pin_mode = GPIO_MODE_IT_FT;
  cfg->GPIO_pin_speed = GPIO_SPEED_LOW;
  cfg->GPIO_pin_pupd_control = GPIO_PUPDR_PD;
  cfg->GPIO_pin_out_type = 0;
  cfg->GPIO_pin_alt_func_mode = 0;
  GPIO_init(&gpio_handle);
  GPIO_irq_interrupt_config(IRQ_NO_EXTI15_10, ENABLE);
  GPIO_irq_priority_config(IRQ_NO_EXTI15_10, 13);

  // LED PB0
  *addr = GPIOE;
  cfg->GPIO_pin_number = 1;
  cfg->GPIO_pin_mode = GPIO_MODE_OUT;
  cfg->GPIO_pin_speed = GPIO_SPEED_LOW;
  cfg->GPIO_pin_pupd_control = GPIO_PUPDR_NONE;
  cfg->GPIO_pin_out_type = GPIO_OP_TYPE_PP;
  cfg->GPIO_pin_alt_func_mode = 0;
  GPIO_init(&gpio_handle);

  // Need to check syscfg -> exticr
  // Need to check EXTI -> FTSR1 and RTSR1 and CPUIMR1
  // Need to check gpioc -> MODER
  // Need to check NVIC ISER and ICER and IPR
}

void EXTI15_10_IRQHandler(void) {
  if (GPIO_irq_handling(13))
    GPIO_toggle_output_pin(GPIOE, 1);
}
